"""added link in session table

Revision ID: 60c930fc8ba7
Revises: 518a3d4c40b9
Create Date: 2025-06-26 15:38:41.780008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60c930fc8ba7'
down_revision = '518a3d4c40b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Session', schema=None) as batch_op:
       batch_op.add_column(sa.Column('link', sa.String(length=255), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Session', schema=None) as batch_op:
        batch_op.drop_column('link')

    # ### end Alembic commands ###
